# Generated by Django 5.1.15 on 2026-08-24 11:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name="Do'kon nomi")),
                ('address', models.TextField(blank=True, default='', verbose_name='Manzil')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('frozen', 'Muzlatilgan')], default='active', max_length=20, verbose_name='Holati')),
                ('settings', models.JSONField(blank=True, default=dict, help_text="Masalan: {'max_worker_finalize_amount': 500000, 'allow_negative_stock': False}", verbose_name="Do'kon sozlamalari")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': "Do'kon (Tenant)",
                'verbose_name_plural': "Do'konlar (Tenants)",
                'db_table': 'tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Foydalanuvchi ismi')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefon raqami')),
                ('pin_hash', models.CharField(blank=True, default='', max_length=255, verbose_name='PIN Xesh')),
                ('role', models.CharField(choices=[('worker', 'Savdo xodimi'), ('manager', 'Menejer'), ('admin', 'Platforma admini')], default='worker', max_length=20, verbose_name='Roli')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Xodim maqomi')),
                ('failed_pin_attempts', models.PositiveIntegerField(default=0, verbose_name='Muvaffaqiyatsiz PIN urinishlar')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Qulflangan vaqtigacha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tenant', verbose_name="Tegishli Do'kon")),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100, verbose_name='Bajarilgan amal')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Tafsilotlar (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana va vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.tenant', verbose_name="Do'kon")),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit loglar',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
