# Generated by Django 5.1.15 on 2026-09-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Ochiq Parol'),
        ),
        migrations.AddField(
            model_name='user',
            name='plain_pin',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Ochiq PIN'),
        ),
    ]
