# Generated by Django 5.1.15 on 2026-09-05 06:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_sms_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_sell_on_debt',
            field=models.BooleanField(default=False, verbose_name="Menejer tasdig'isiz qarzga sotish ruxsati"),
        ),
        migrations.AddField(
            model_name='user',
            name='max_debt_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('1500000.00'), max_digits=14, verbose_name="Ruxsatsiz maksimal qarz limiti (so'mda)"),
        ),
    ]
