# Generated by Django 5.1.15 on 2026-08-24 11:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baskets', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('debt', 'Qarz'), ('mixed', 'Aralash (Naqd + Qarz/Karta)')], max_length=20, verbose_name="To'lov turi")),
                ('cash_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name="Naqd to'langan summa")),
                ('card_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name="Karta orqali to'langan summa")),
                ('debt_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Qarzga yozilgan summa')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Chegirma summasi')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Jami yakuniy summa')),
                ('status', models.CharField(choices=[('completed', 'Muvaffaqiyatli yakunlangan'), ('refunded', 'Qaytarilgan (Refund)'), ('pending_approval', "Menejer tasdig'ini kutmoqda")], default='completed', max_length=30, verbose_name='Tranzaksiya holati')),
                ('client_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Mijoz ismi')),
                ('client_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Mijoz telefoni')),
                ('items_snapshot', models.JSONField(blank=True, default=list, verbose_name="Sotilgan tovarlar ro'yxati (snapshot)")),
                ('refund_reason', models.TextField(blank=True, default='', verbose_name='Qaytarish sababi')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Qaytarilgan sana')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan menejer')),
                ('basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='baskets.basket', verbose_name='Tegishli savat')),
                ('finalized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finalized_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Savdoni yakunlagan/yuborgan xodim')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='core.tenant', verbose_name="Do'kon")),
            ],
            options={
                'verbose_name': 'Savdo tranzaksiyasi',
                'verbose_name_plural': 'Savdo tranzaksiyalari',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='transaction_tenant__fb4178_idx'), models.Index(fields=['tenant', 'status'], name='transaction_tenant__bc85d9_idx'), models.Index(fields=['tenant', 'finalized_by'], name='transaction_tenant__77bfdb_idx')],
            },
        ),
    ]
