# Generated by Django 5.1.15 on 2026-08-24 11:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('client_name', models.CharField(max_length=255, verbose_name='Mijoz ismi')),
                ('client_phone', models.CharField(max_length=30, verbose_name='Mijoz telefon raqami')),
                ('total_debt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Jami olingan qarz summasi')),
                ('remaining_debt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name="Qolgan (to'lanmagan) qarz summasi")),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Qarzni to'lash muddati")),
                ('last_sms_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi SMS yuborilgan vaqt')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Izoh/Qaydlar')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='core.tenant', verbose_name="Do'kon")),
            ],
            options={
                'verbose_name': 'Qarz',
                'verbose_name_plural': 'Qarzlar',
                'db_table': 'debts',
                'ordering': ['-remaining_debt', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa')),
                ('type', models.CharField(choices=[('borrowed', 'Qarz olindi'), ('paid', "Qarz to'landi")], max_length=20, verbose_name='Amal turi')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta')], default='cash', max_length=20, verbose_name="To'lov turi")),
                ('notes', models.TextField(blank=True, default='', verbose_name="To'lov izohi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana va vaqt')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='debts.debt', verbose_name='Qarz daftari yozuvi')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan xodim')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_histories', to='transactions.transaction', verbose_name='Tegishli savdo')),
            ],
            options={
                'verbose_name': 'Qarz harakati tarixi',
                'verbose_name_plural': 'Qarzlar tarixi',
                'db_table': 'debt_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['tenant', 'client_phone'], name='debts_tenant__ad5eed_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['tenant', 'remaining_debt'], name='debts_tenant__cb5302_idx'),
        ),
    ]
