# Generated by Django 5.1.15 on 2026-08-24 11:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('purchase_unit', models.CharField(help_text='Masalan: qop, tonna, rulon, blok', max_length=50, verbose_name='Kelish birligi')),
                ('sale_unit', models.CharField(help_text='Masalan: dona, metr, kg, litr', max_length=50, verbose_name='Sotish birligi')),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text="1 kelish birligi nechta sotish birligiga tengligi (masalan 1 qop = 50 kg bo'lsa: 50)", max_digits=12, verbose_name='Konversiya koeffitsienti')),
                ('price_per_sale_unit', models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Sotish birligi narxi (so'mda)")),
                ('current_stock', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Joriy qoldiq (sotish birligida)')),
                ('reserved_stock', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Band qilingan qoldiq (savatchalarda)')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Shtrix kod (Barcode)')),
                ('qr_code', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='QR kod')),
                ('low_stock_threshold', models.DecimalField(decimal_places=4, default=Decimal('5.0000'), max_digits=14, verbose_name='Kam qoldiq chegarasi')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Arxivlanganmi')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='core.tenant', verbose_name="Do'kon")),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Eski narx')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Yangi narx')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="O'zgargan sana")),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="O'zgartiruvchi xodim")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': "Narx o'zgarishi tarixi",
                'verbose_name_plural': 'Narxlar tarixi',
                'db_table': 'price_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('kirim', 'Kirim'), ('chiqim', 'Chiqim'), ('tuzatish', 'Inventarizatsiya tuzatishi')], max_length=20, verbose_name='Harakat turi')),
                ('purchase_unit_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Kelish birligidagi miqdor')),
                ('sale_unit_amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Sotish birligidagi miqdor')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Sabab/Izoh (inventarizatsiya tuzatishi uchun)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana va vaqt')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Bajaruvchi xodim')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Sklad harakati',
                'verbose_name_plural': 'Sklad harakatlari',
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'barcode'], name='products_tenant__bb13e8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'qr_code'], name='products_tenant__45720b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'is_archived'], name='products_tenant__872228_idx'),
        ),
    ]
