# Generated by Django 5.1.15 on 2026-09-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_plain_password_user_plain_pin'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False), models.Q(('barcode', ''), _negated=True)), fields=('tenant', 'barcode'), name='unique_product_barcode_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('qr_code__isnull', False), models.Q(('qr_code', ''), _negated=True)), fields=('tenant', 'qr_code'), name='unique_product_qrcode_per_tenant'),
        ),
    ]
