# Generated by Django 5.1.15 on 2026-08-24 11:42

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mijoz ismi')),
                ('client_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mijoz telefon raqami')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan'), ('stale', 'Eskirgan'), ('pending_approval', "Menejer tasdig'ini kutmoqda")], default='active', max_length=30, verbose_name='Savat holati')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Savat',
                'verbose_name_plural': 'Savatlar',
                'db_table': 'baskets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=14, verbose_name='Miqdor (sotish birligida)')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Savat elementi',
                'verbose_name_plural': 'Savat elementlari',
                'db_table': 'basket_items',
                'ordering': ['added_at'],
            },
        ),
    ]
