# Generated by Django 5.1.15 on 2026-08-24 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baskets', '0001_initial'),
        ('core', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='core.tenant', verbose_name="Do'kon"),
        ),
        migrations.AddField(
            model_name='basket',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to=settings.AUTH_USER_MODEL, verbose_name='Savdo xodimi'),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='baskets.basket', verbose_name='Tegishli savat'),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='products.product', verbose_name='Mahsulot'),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Skanerlagan xodim'),
        ),
        migrations.AddIndex(
            model_name='basket',
            index=models.Index(fields=['tenant', 'worker', 'status'], name='baskets_tenant__d6914c_idx'),
        ),
        migrations.AddIndex(
            model_name='basket',
            index=models.Index(fields=['tenant', 'status'], name='baskets_tenant__2427a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together={('basket', 'product')},
        ),
    ]
